---
apiVersion: v1
kind: Secret
metadata:
  name: dev-arc-kafka
  labels:
    app: dev-arc-kafka
    app.kubernetes.io/component: dev-arc-kafka
    app.kubernetes.io/instance: dev-arc-kafka
    app.kubernetes.io/part-of: dev-arc
data:
stringData:
  KAFKA_BOOTSTRAP_SERVER: 'dev-arc-kafka-kafka-bootstrap:9092'
  KAFKA_SECURITY_PROTOCOL: 'PLAINTEXT'
  KAFKA_SASL_MECHANISM: ''
  KAFKA_USERNAME: ''
  KAFKA_PASSWORD: ''
  KAFKA_TOPIC_IMAGES: images
  KAFKA_TOPIC_OBJECTS: objects
