---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from":{
            "kind":"ImageStreamTag",
            "name":"dev-arc-kafkaconsumer:latest"
          },
          "fieldPath":"spec.template.spec.containers[?(@.name==\"dev-arc-kafkaconsumer\")].image"
        }
      ]
  name: dev-arc-kafkaconsumer
  labels:
    app: dev-arc-kafkaconsumer
    app.kubernetes.io/component: dev-arc-kafkaconsumer
    app.kubernetes.io/instance: dev-arc-kafkaconsumer
    app.kubernetes.io/part-of: dev-arc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dev-arc
      deployment: dev-arc-kafkaconsumer
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app.kubernetes.io/part-of: dev-arc
        deployment: dev-arc-kafkaconsumer
    spec:
      containers:
        - name: dev-arc-kafkaconsumer
          image: 'dev-arc-kafkaconsumer:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env:
            - name: KAFKA_TOPIC_OBJECTS
              valueFrom:
                secretKeyRef:
                  name: dev-arc-kafka
                  key: KAFKA_TOPIC_OBJECTS
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dev-arc-kafka
                  key: KAFKA_USERNAME
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                secretKeyRef:
                  name: dev-arc-kafka
                  key: KAFKA_BOOTSTRAP_SERVER
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-arc-kafka
                  key: KAFKA_PASSWORD
            - name: KAFKA_SASL_MECHANISM
              valueFrom:
                secretKeyRef:
                  name: dev-arc-kafka
                  key: KAFKA_SASL_MECHANISM
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: dev-arc-kafka
                  key: KAFKA_SECURITY_PROTOCOL
            - name: KAFKA_TOPIC_IMAGES
              valueFrom:
                secretKeyRef:
                  name: dev-arc-kafka
                  key: KAFKA_TOPIC_IMAGES
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
