---
kind: Service
apiVersion: v1
metadata:
  name: dev-arc-kafkaconsumer
  labels:
    app: dev-arc-kafkaconsumer
    app.kubernetes.io/component: dev-arc-kafkaconsumer
    app.kubernetes.io/instance: dev-arc-kafkaconsumer
    app.kubernetes.io/part-of: dev-arc
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/part-of: dev-arc
    deployment: dev-arc-kafkaconsumer
status:
  loadBalancer: {}
