apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kafka
#  namespace: arc-test01
spec:
  destination:
    # namespace: arc-test01
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      # I believe I came across a bug then the line below is true
      recurse: false
    path: ar-coupons/dev/kafka
    # repoURL: https://github.com/rh-aiservices-bu/car-deploy.git
    repoURL: http://gogs:3000/gogs/arc-deploy.git
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
      - /spec/template/spec/containers/0/image
