apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model
  namespace: argocd-instance
spec:
  destination:
    namespace: argocd-instance
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      # I believe I came across a bug then the line below is true
      recurse: false
    path: manifests
    repoURL: https://github.com/rh-aiservices-bu/car-deploy.git
    targetRevision: dev
  syncPolicy:
    automated: {}
      #prune: true
      #selfHeal: true