apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gogs
  # namespace: arc-test01
spec:
  project: default
  source:
    repoURL: https://github.com/rh-aiservices-bu/arc-deploy.git
    targetRevision: dev
    path: gogs
    directory:
      # I believe I came across a bug then the line below is true
      recurse: false
  destination:
    # namespace: arc-test01
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 1
        maxDuration: 10m
      limit: 120
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
      - /spec/template/spec/containers/0/image
