---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline
  # namespace: arc-test01
spec:
  destination:
    # namespace: arc-test01
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://gogs:3000/gogs/arc-deploy.git
    targetRevision: dev
    path: ar-coupons/tekton
    directory:
      # I believe I came across a bug then the line below is true
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 1
        maxDuration: 10m
      limit: 120
