---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: dev-arc-frontend
  labels:
    app: dev-arc-frontend
    app.kubernetes.io/component: dev-arc-frontend
    app.kubernetes.io/instance: dev-arc-frontend
    app.kubernetes.io/part-of: dev-arc
spec:
  nodeSelector: null
  postCommit: {}
  resources: {}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:14-ubi8'
  source:
    type: Git
    git:
      uri: 'https://github.com/rh-aiservices-bu/arc-app'
      ref: dev
  output:
    to:
      kind: ImageStreamTag
      name: 'dev-arc-frontend:latest'
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
