apiVersion: v1
kind: ConfigMap
metadata:
  name: arc-frontend
  labels:
    app: arc-frontend
    app.kubernetes.io/component: arc-frontend
    app.kubernetes.io/instance: arc-frontend
    app.kubernetes.io/part-of: arc-dev
data:
  OBJECT_DETECTION_URL: "http://arc-model:8080/predictions"
