apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: arc-frontend
    app.kubernetes.io/component: arc-frontend
    app.kubernetes.io/instance: arc-frontend
    app.kubernetes.io/part-of: arc-dev
  name: arc-frontend
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: arc-frontend
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None