---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: rest
    app.kubernetes.io/part-of: rest
  name: rest-image
spec:
  lookupPolicy:
    local: true