---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"car-rest:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"car-rest\")].image"}]
  name: car-rest
  labels:
    app: car-rest
    app.kubernetes.io/component: car-rest
    app.kubernetes.io/instance: car-rest
    app.kubernetes.io/part-of: car
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: car
      deployment: car-rest
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: car
        deployment: car-rest
    spec:
      containers:
        - name: car-rest
          image: 'rest-image:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
