apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-rest1
  namespace: argocd-instance
spec:
  destination:
    namespace: argotest01
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: manifests
    repoURL: https://github.com/rh-aiservices-bu/car-deploy.git
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true