apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: objects
  labels:
    strimzi.io/cluster: object-detection
    app: object-detection-kafka
spec:
  partitions: 1
  replicas: 1
  topicName: objects
  config:
    retention.ms: 7200000