apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: objects
  labels:
    strimzi.io/cluster: car
    app: car-kafka
    app.kubernetes.io/part-of: car
spec:
  partitions: 1
  replicas: 1
  topicName: objects
  config:
    retention.ms: 7200000