apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
