---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: model-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: deployment-name
      type: string
      description: name of the deployment to be patched
      default: "k8s"
  tasks:
    - name: start
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: git-clone-model
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - start
    - name: lint-and-syntax-model
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - git-clone-model
    - name: build-model-image
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - lint-and-syntax-model
    - name: sanity-check-model
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - build-model-image
    - name: performance-check-model
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - build-model-image
    - name: security-scan-model
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - build-model-image
    - name: trigger-move-to-production
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - security-scan-model
        - performance-check-model
        - sanity-check-model
