---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: syntax-pipeline
spec:
  params:
    - name: git-instance-prefix
      type: string
      description: >-
        Whether to use github or gogs.
        Use either https://github.com/rh-aiservices-bu
        or
        http://gogs:3000/gogs
      default: "http://gogs:3000/gogs"
    - name: git-repo-name
      type: string
      description: >-
        something like arc-deploy or arc-model
      default: "arc-deploy"
    - name: git-ref
      type: string
      description: >-
        git ref to use. (branch, label, commit, etc..)
      default: "dev"
  workspaces:
    - name: shared-workspace
  tasks:
    ## get repo
    - name: git-clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.git-instance-prefix)/$(params.git-repo-name)"
        - name: revision
          value: "$(params.git-ref)"
        - name: subdirectory
          value: "$(params.git-repo-name)"
        - name: deleteExisting
          value: "true"
    ## yaml-lint
    - name: yaml-lint-deploy
      taskRef:
        name: yaml-lint
      runAfter:
        - git-clone-repo
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: args
          value: ["$(params.git-repo-name)"]
    - name: python-black-run
      taskRef:
        name: python-black
      runAfter:
        - git-clone-repo
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: args
          value: ["$(params.git-repo-name)", "--check", "--diff"]
  finally:
    - name: cleanup-test
      taskRef:
        name: cleanup
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
