---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: syntax-pipeline-github-arc-deploy
spec:
  pipelineRef:
    name: syntax-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: source-pvc1
  params:
    - name: git-instance-prefix
      value: https://github.com/rh-aiservices-bu
    - name: git-ref
      value: dev
    - name: git-repo-name
      value: arc-deploy
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: syntax-pipeline-gogs-arc-deploy
spec:
  pipelineRef:
    name: syntax-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: source-pvc2
  params:
    - name: git-instance-prefix
      value: http://gogs:3000/gogs
    - name: git-ref
      value: dev
    - name: git-repo-name
      value: arc-deploy
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: syntax-pipeline-github-arc-model
spec:
  pipelineRef:
    name: syntax-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: source-pvc1
  params:
    - name: git-instance-prefix
      value: https://github.com/rh-aiservices-bu
    - name: git-ref
      value: dev
    - name: git-repo-name
      value: arc-model
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: syntax-pipeline-gogs-arc-model
spec:
  pipelineRef:
    name: syntax-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: source-pvc2
  params:
    - name: git-instance-prefix
      value: http://gogs:3000/gogs
    - name: git-ref
      value: dev
    - name: git-repo-name
      value: arc-model
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: syntax-pipeline-github-arc-kafka
spec:
  pipelineRef:
    name: syntax-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: source-pvc1
  params:
    - name: git-instance-prefix
      value: https://github.com/rh-aiservices-bu
    - name: git-ref
      value: dev
    - name: git-repo-name
      value: arc-kafka
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: syntax-pipeline-gogs-arc-kafka
spec:
  pipelineRef:
    name: syntax-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: source-pvc2
  params:
    - name: git-instance-prefix
      value: http://gogs:3000/gogs
    - name: git-ref
      value: dev
    - name: git-repo-name
      value: arc-kafka
