---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: syntax-pipeline
spec:
  params:
    - name: git-instance-prefix
      type: string
      description: >-
        Whether to use github or gogs.
        Use either https://github.com/rh-aiservices-bu
        or
        http://gogs:3000/gogs
      default: "http://gogs:3000/gogs"
    - name: git-ref
      type: string
      description: >-
        git ref to use. (branch, label, commit, etc..)
      default: "dev"
  workspaces:
    - name: shared-workspace
      # persistentvolumeclaim:
      #   claimName: source-pvc
  tasks:
    ## get repo
    - name: fetch-deploy-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.git-instance-prefix)/arc-deploy"
          # value: https://github.com/rh-aiservices-bu/arc-deploy
        - name: revision
          value: "$(params.git-ref)"
        - name: subdirectory
          value: "deploy"
        - name: deleteExisting
          value: "true"
    ## yaml-lint
    - name: yaml-lint-deploy
      taskRef:
        name: yaml-lint
      runAfter:
        - fetch-deploy-repo
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: args
          value: ["."]
    - name: fetch-model-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.git-instance-prefix)/arc-rest"
          # value: https://github.com/rh-aiservices-bu/arc-rest
        - name: subdirectory
          value: "rest"
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "$(params.git-ref)"
    - name: python-black-run
      taskRef:
        name: python-black
      runAfter:
        - fetch-model-repo
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: args
          value: [".", "--check", "--diff"]
  finally:
    - name: cleanup-test
      taskRef:
        name: cleanup
        # - name: image
        #   value: python:3.8-slim
