# apiVersion: v1
apiVersion: template.openshift.io/v1
kind: Template

labels:
  application: arc-common

metadata:
  name: arc-common

parameters:
  - name: KAFKA_BOOTSTRAP_SERVER
  - name: KAFKA_SECURITY_PROTOCOL
  - name: KAFKA_SASL_MECHANISM
  - name: KAFKA_USERNAME
  - name: KAFKA_PASSWORD
  - name: KAFKA_TOPIC_IMAGES
  - name: KAFKA_TOPIC_OBJECTS
  - name: OBJECT_DETECTION_URL
    value: "http://arc-rest:8080/predictions"

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: arc-kafka
      labels:
        app: arc-common
        app.kubernetes.io/component: arc-common
        app.kubernetes.io/instance: arc-common
        app.kubernetes.io/part-of: arc
    data:
    stringData:
      KAFKA_BOOTSTRAP_SERVER: ${KAFKA_BOOTSTRAP_SERVER}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      KAFKA_TOPIC_IMAGES: ${KAFKA_TOPIC_IMAGES}
      KAFKA_TOPIC_OBJECTS: ${KAFKA_TOPIC_OBJECTS}

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: arc-rest
      labels:
        app: arc-common
        app.kubernetes.io/component: arc-common
        app.kubernetes.io/instance: arc-common
        app.kubernetes.io/part-of: arc
    data:
      OBJECT_DETECTION_URL: ${OBJECT_DETECTION_URL}

